### ISSUE TITLE
Error in Angular typescript compilation in 3.0.2

### ISSUE THREAD

**Issue by billdwhite** [greensock/GSAP#340]
When I upgrade from 3.0.1 to 3.0.2 in Angular 8, I see this after compilation.

```
ERROR in ../node_modules/gsap/types/animation.d.ts:42:33 - error TS2304: Cannot find name 'Omit'.

42     then(onFulfilled?: (result: Omit<this, "then">) => any): Promise<this>;
```

I am using Angular 8.2.14 and this did not occur in 3.0.1

**Comment by OSUblake** [comment]
Hi @billdwhite Can you confirm what version of TypeScript you are using?

`Omit` was added to [TypeScript 3.5](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-5.html#the-omit-helper-type). If you can't upgrade, you can add the `Omit` type to a .d.ts file in your project.

```ts
type Omit<T, K extends keyof any> = Pick<T, Exclude<keyof T, K>>;
```

**Comment by billdwhite** [comment]
Indeed, I have typescript 3.4.5;  Upgrading to 3.5.3 resolves the issue.  Thanks!
