### ISSUE TITLE
MotionPathPlugin throws an error when tweening a plain object

### ISSUE THREAD

**Issue by AllenWilliamson** [greensock/GSAP#370]
When tweening anything other than a DOM element with MotionPathPlugin, the error `target.getAttribute is not a function` is thrown.

The example below works in `gsap@3.0.5` but throws the error in the latest release (`gsap@3.2.4`).

```js
let animatedObject = { x: 0, y: 0 };
gsap.to(animatedObject, {
    duration: 0.5,
    motionPath: [
        { x: 0, y: 0 },
        { x: 2, y: 5 },
        { x: 10, y: 10 },
    ],
});
```

**Comment by ZachSaucier** [comment]
Hey Allen.

Your code [works just fine for me](https://codepen.io/GreenSock/pen/QWbQrJW?editors=0010). Can you please provide any additional information needed to create the error that you're getting?

**Comment by AllenWilliamson** [comment]
Starting with a fresh node_modules fixed the issue. I should have tried that first before posting. Not sure what was the cause there but thanks for the quick reply.

**Comment by ZachSaucier** [comment]
I'm not sure what could cause the issue either. I'm glad you got it working!

**Comment by ZachSaucier** [comment]
Again, [I can't reproduce](https://codepen.io/GreenSock/pen/GRoVjXV?editors=0010). Can you please make a minimal demo @isjackwild?

**Comment by isjackwild** [comment]
Hi, I realise that it's when you don't have an x and y property on the object you're animating. I'm trying to use it as I used to previously use Bezier plugin to animate arbitrary values 'through' other values (for use with THREE.js object camera animation — but not directly motion itself)

**Comment by ZachSaucier** [comment]
Thanks! [I can reproduce that](https://codepen.io/GreenSock/pen/BaKBWvB?editors=0010). We'll get it fixed ASAP.

**Comment by isjackwild** [comment]
Thanks! Sorry it was on my list to make a reproduction of this for you
today but didn't get round to it yet. Thanks for doing that though :)

**Comment by jackdoyle** [comment]
This should be resolved in the next release which you can preview at https://assets.codepen.io/16327/gsap-latest-beta.min.js (the issue was in the core, not MotionPathPlugin). Sorry about any confusion there. Thanks for the reduced test case, @ZachSaucier

**Comment by isjackwild** [comment]
Fantastic, thanks!
